[stage-one]
results = [ [ "h", "b", "-", "-", "-", "-",], [ "u", "b", "-", "-", "-", "-",], [ "h", "b", "-", "-", "-", "-",], [ "u", "h", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",],]
winners = [ [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",],]

[stage-two]
round-of-16 = [ "-", "-", "-", "-", "-", "-", "-", "-",]
quarter-final = [ "-", "-", "-", "-",]
semi-final = [ "-", "-",]

[finals]
bronse-final = "-"
final = "-"

[info]
user = "actual"
