[stage-one]
results = [ [ "h", "b", "h", "h", "h", "b",], [ "u", "u", "h", "b", "b", "h",], [ "h", "h", "h", "h", "b", "b",], [ "h", "h", "h", "h", "b", "b",], [ "h", "h", "h", "b", "b", "h",], [ "h", "h", "h", "b", "b", "h",], [ "h", "b", "h", "h", "h", "b",], [ "h", "h", "u", "h", "b", "b",],]
winners = [ [ "Uruguay", "Russia",], [ "Spain", "Portugal",], [ "France", "Peru",], [ "Argentina", "Croatia",], [ "Brazil", "Switzerland",], [ "Germany", "Mexico",], [ "England", "Belgium",], [ "Poland", "Colombia",],]

[stage-two]
round-of-16 = [ "Portugal", "Spain", "France", "Argentina", "Brazil", "Germany", "England", "Belgium",]
quarter-final = [ "Portugal", "Argentina", "Brazil", "Germany",]
semi-final = [ "Brazil", "Germany",]

[finals]
bronse-final = "Argentina"
final = "Brazil"

[info]
user = "TMatthey"
