[stage-one]
results = [ [ "h", "b", "b", "h", "u", "b",], [ "u", "b", "h", "b", "b", "h",], [ "h", "b", "h", "h", "b", "b",], [ "h", "h", "u", "b", "b", "u",], [ "h", "h", "h", "b", "b", "u",], [ "h", "h", "h", "b", "b", "h",], [ "h", "b", "h", "h", "u", "b",], [ "h", "h", "u", "b", "b", "b",],]
winners = [ [ "Uruguay", "Egypt",], [ "Portugal", "Spain",], [ "France", "Denmark",], [ "Argentina", "Croatia",], [ "Brazil", "Costa Rica",], [ "Germany", "Mexico",], [ "Belgium", "England",], [ "Colombia", "Poland",],]

[stage-two]
round-of-16 = [ "Spain", "Portugal", "France", "Argentina", "Brazil", "Germany", "Belgium", "England",]
quarter-final = [ "France", "Argentina", "Brazil", "Germany",]
semi-final = [ "Brazil", "Germany",]

[finals]
bronse-final = "Argentina"
final = "Brazil"

[info]
user = "Bjorn-Tore"
