[stage-one]
results = [ [ "h", "b", "h", "h", "u", "u",], [ "b", "h", "h", "b", "b", "h",], [ "h", "u", "h", "h", "u", "h",], [ "b", "h", "h", "u", "b", "b",], [ "h", "b", "h", "b", "b", "h",], [ "h", "u", "h", "u", "b", "u",], [ "h", "b", "h", "h", "b", "b",], [ "h", "h", "h", "h", "u", "u",],]
winners = [ [ "Russia", "Uruguay",], [ "Spain", "Portugal",], [ "France", "Denmark",], [ "Croatia", "Argentina",], [ "Brazil", "Switzerland",], [ "Germany", "Sweden",], [ "Belgium", "England",], [ "Poland", "Colombia",],]

[stage-two]
round-of-16 = [ "Portugal", "Spain", "France", "Croatia", "Brazil", "Germany", "Belgium", "England",]
quarter-final = [ "France", "Spain", "Brazil", "Germany",]
semi-final = [ "Brazil", "Germany",]

[finals]
bronse-final = "France"
final = "Brazil"

[info]
user = "AGilje"
