[stage-one]
results = [ [ "h", "b", "h", "h", "-", "-",], [ "u", "b", "h", "-", "-", "-",], [ "h", "b", "-", "-", "-", "-",], [ "u", "h", "-", "-", "-", "-",], [ "u", "b", "-", "-", "-", "-",], [ "b", "h", "-", "-", "-", "-",], [ "h", "b", "-", "-", "-", "-",], [ "b", "b", "-", "-", "-", "-",],]
winners = [ [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",],]

[stage-two]
round-of-16 = [ "-", "-", "-", "-", "-", "-", "-", "-",]
quarter-final = [ "-", "-", "-", "-",]
semi-final = [ "-", "-",]

[finals]
bronse-final = "-"
final = "-"

[info]
user = "actual"
