[stage-one]
results = [ [ "u", "b", "b", "h", "u", "b",], [ "b", "u", "h", "b", "b", "h",], [ "h", "b", "h", "h", "b", "h",], [ "u", "u", "h", "b", "b", "u",], [ "h", "u", "h", "h", "b", "u",], [ "h", "h", "h", "b", "b", "h",], [ "h", "b", "h", "h", "u", "h",], [ "h", "h", "u", "u", "b", "b",],]
winners = [ [ "Uruguay", "Egypt",], [ "Spain", "Portugal",], [ "France", "Denmark",], [ "Argentina", "Iceland",], [ "Brazil", "Serbia",], [ "Germany", "Mexico",], [ "England", "Belgium",], [ "Colombia", "Poland",],]

[stage-two]
round-of-16 = [ "Uruguay", "Spain", "France", "Denmark", "Brazil", "Germany", "England", "Belgium",]
quarter-final = [ "France", "Spain", "Brazil", "Germany",]
semi-final = [ "Brazil", "Germany",]

[finals]
bronse-final = "Spain"
final = "Germany"

[info]
user = "Lars Magnus"
