[stage-one]
results = [ [ "h", "b", "-", "-", "-", "-",], [ "u", "b", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",], [ "-", "-", "-", "-", "-", "-",],]
winners = [ [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",], [ "-", "-",],]

[stage-two]

[finals]

[info]
user = "actual"
